server:
  port: 80
  context-path: /app/api
swagger.enable: true
spring:
 #jpa配置
  jpa:
      show-sql: true
      generate-ddl: true
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.42.142.228:3306/hrt?characterEncoding=utf8
    username: youyi
    password: youyi
mybatis:
  mapper-locations: classpath:mapper/*.xml
